### ISSUE TITLE
types.xsd not found in schema

### ISSUE THREAD

**Issue by im-portthis** [tuffnatty/xsd_to_django_model#1]
$> python xsd_to_django_model.py schema.xsd types.xsd
`ERROR:__main__:EXCEPTION: types.xsd not found in schema`

schema.xsd:
<xs:import namespace="types" schemaLocation="types.xsd"/>

**Comment by tuffnatty** [comment]
The arguments after the first one should be type names, not XSD file names, e.g.:
`python xsd_to_django_model.py schema.xsd ATopLevelTypeName`
