### ISSUE TITLE
Question: how to pick `xsd_type`?

### ISSUE THREAD

**Issue by jamesbraza** [tuffnatty/xsd_to_django_model#11]
I am trying to convert https://ftp.expasy.org/databases/cellosaurus/cellosaurus.xsd to a Django model.

I am not sure what to enter for `xsd_type`.  The below is not working out for me:

```bash
xsd_to_django_model.py cellosaurus.xsd /Cellosaurus
```

Any pointers on how to pick `xsd_type`?

**Comment by tuffnatty** [comment]
Hi @jamesbraza . You did the right thing. The XSD itself is not very simple, somewhat buggy, and have hit some edge cases with xsd_to_django_model, so I decided to fix the stuff and add it as an example here:
https://github.com/tuffnatty/xsd_to_django_model/tree/master/examples/cellosaurus

**Comment by jamesbraza** [comment]
Wow, that is so awesome @tuffnatty, thank you!!  I will take a look at this next week, appreciate you for fixing this up and making that example

**Comment by jamesbraza** [comment]
Thanks again @tuffnatty for your help with this, closing this out
